language: csharp
dist: xenial
solution: Wallee.sln
git:
    quiet: true
install:
    - nuget restore Wallee.sln
    - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
    - dotnet msbuild /t:restore Wallee.sln
    - dotnet msbuild Wallee.sln /t:build /p:Configuration=Release
