language: csharp
sudo: false
mono:
  - latest
dotnet: 2.1.101	
solution: Customweb.Wallee.sln
script:
  - dotnet restore
  - /bin/sh ./build.sh
  - /bin/sh ./test.sh
deploy:
  skip_cleanup: true
  provider: script
  script:
    - /bin/sh ./deploy.sh
  on:
    tags: true
